### ISSUE TITLE
Getting an error while retrieving all product identifiers

### ISSUE THREAD

**Issue by Jigs6720** [chargebee/chargebee-react-native#126]
Error: Invalid catalog version
    at Object.promiseMethodWrapper [as retrieveProductIdentifiers] (NativeModules.js:105:51)
    at Function.<anonymous> (Chargebee.ts:68:33)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:16)
    at _next (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at tryCallTwo (core.js:45:5)
    at doResolve (core.js:200:13)
    at new Promise (core.js:66:3)
    at Function.<anonymous> (asyncToGenerator.js:21:12)

following is the code:
 const queryParams = new Map();
    queryParams.set("limit", "1");
    try {
      const result = await Chargebee.retrieveProductIdentifiers(queryParams);
      console.log(result);
    } catch (error) {
      console.log(error);
    }

**Comment by Jigs6720** [comment]
@cb-haripriyan yes it is configure properly. i am still getting this error.

**Comment by cb-haripriyan** [comment]
@Jigs6720 Can you share the domain you are trying on?

**Comment by Jigs6720** [comment]
this is the configure method Chargebee.configure({
  site: "medentry-uk-test",
  publishableApiKey: "test_aDEDK8834jxcuKcnDr1GOb5bJSQcdDyy6",
});

**Comment by cb-haripriyan** [comment]
@Jigs6720 Can you check the response of this method?
I see in our system that the error "SDK Key is empty" is being returned. 

And can you check the configuration section [here](https://github.com/chargebee/chargebee-react-native#configuring-sdk)?

The `configure` method takes in 4 parameters, including the Android and iOS SDK Keys. Your implementation seems to missing that.

**Comment by Jigs6720** [comment]
@cb-haripriyan so is iosSdkKey and androidSdk Key is mandatory fields?

**Comment by cb-saisrikant** [comment]
@Jigs6720 Glad to connect with you! Yes SDK key is mandatory.
Please note that you need to connect your app to Chargebee and generate the SDK key which is same as the App id. Please refer to [this link](https://www.chargebee.com/docs/2.0/mobile-app-store-connect.html) to understand how to connect your app to Chargebee. We will be happy to get on a call and help you if needed. Please let us know. Thanks

**Comment by Jigs6720** [comment]
@cb-saisrikant Thank you for this clarification.

**Comment by cb-haripriyan** [comment]
Closing this issue since it was related to incomplete configuration.

Please create a new issue if you face any other issues.
