### ISSUE TITLE
I can not retrieve products even though i can retrieve the product identifiers

### ISSUE THREAD

**Issue by samynaj** [chargebee/chargebee-react-native#153]
I have an issue retrieving products on my iOS platform even though I can retrieve their identifiers.
this is how i fetch the product identifiers and i get them back:
const fetchProductsIdentifiers = async () => {
    const queryParams = new Map();
    queryParams.set("limit", "10");
    try {
      const result = await Chargebee.retrieveProductIdentifiers(queryParams);
      console.log("product identifiers:", result);
    } catch (error) {
      console.log("Error when fetching product identifiers", error);
      console.log(
        "=========================",
        Platform.OS,
        "========================="
      );
    }
  };

but when i call the fetchProducts api with the array returned from the endpoint, i get an [Error: Products not found.]
  const fetchProducts = async () => {
    try {
      const productList = await Chargebee.retrieveProducts([
        "Gold_999_1m",
        "Silver_199_1m",
        "Gold_999_1y",
        "Half_yearly_plan_1",
        "Yearly_plan_1",
        "Monthly_plan_1",
        "Weekly_plan_1",
        "Daily_plan_1",
      ]);
      setProductIds(productList);
      console.log("products:", productList);
    } catch (error) {
      console.log("Error when fetching product", error);
      console.log(
        "=========================",
        Platform.OS,
        "========================="
      );
    }
  };

I have the products i have called all setup on app store connect
So I don't know what might be wrong.

**Comment by cb-haripriyan** [comment]
Hi @samynaj 

Does this happen for iOS or Android or both ?

**Comment by cb-haripriyan** [comment]
@samynaj  The 'retrieveProducts' API depends on the native iOS/Android SDK's method to fetch the products. If it doesn't return any products for iOS, it can be due to missing AppStore configurations. Can you verify the following cases in your AppStore connect page?
    - Finance Agreement is accepted in Appstore Connect and the status should show active for your apps.
    - App Bundle ID matches with the Bundle ID in App Store Connect.
    - Changing the reference name in App Store Connect can also cause products to not fetch on iOS. Create a new product with a different identifier, fill out any missing metadata, and attempt to fetch products again.
    
If none of these seem to solve the problem, we can get on a call to look into this.

**Comment by kauan777** [comment]
i have same problem

**Comment by als260502** [comment]
Mr Kauan did you managed to solve the problem?

**Comment by lukasfkt** [comment]
I'm having the same problem too, please, can anyone help us??? :((

**Comment by cb-haripriyan** [comment]
Hello Buzzvel folks @kauan777 / @als260502 / @ViniciusGG / @lukasfkt - 
Can you please confirm if the points mentioned in https://github.com/chargebee/chargebee-react-native/issues/153#issuecomment-1740503904 have been setup correctly?

If all of these are setup correctly, and issue still persist, recommend getting on a call and solving your particular case.

**Comment by als260502** [comment]
> Hello Buzzvel folks @kauan777 / @als260502 / @ViniciusGG / @lukasfkt - Can you please confirm if the points mentioned in [#153 (comment)](https://github.com/chargebee/chargebee-react-native/issues/153#issuecomment-1740503904) have been setup correctly?
> 
> If all of these are setup correctly, and issue still persist, recommend getting on a call and solving your particular case.

Hello, how and when can we schedule this call?

**Comment by cb-haripriyan** [comment]
Hey @als260502 -
I believe that our support team is in touch with your team. You can set up the call through them. If not you can get in touch with us through our support https://support.chargebee.com

**Comment by cb-haripriyan** [comment]
Closing this as this is related to App Store configuration.
