### ISSUE TITLE
I can't delete Product Family in Platform

### ISSUE THREAD

**Issue by kauan777** [chargebee/chargebee-react-native#157]
![image](https://github.com/chargebee/chargebee-react-native/assets/74926453/488e604f-8761-42a6-b28a-db0a9ad02856)

How can i resolve it? i don't found a options to delete items

**Comment by cb-haripriyan** [comment]
Hi @kauan777 - 
Since the plans are created from the Google Play Store, we cannot delete them via Chargebee. If you would want to delete, you can reach out to our support, with the relevant details.
Please refer to our [FAQs](https://www.chargebee.com/docs/2.0/mobile-faq.html) for more details.

**Comment by kauan777** [comment]
Thanks very much! I will do it
