### ISSUE TITLE
Support Google Play Billing Library v6 is Required by Aug 31, 2024

### ISSUE THREAD

**Issue by MarkAuderli** [chargebee/chargebee-react-native#180]
According to this [link](https://developer.android.com/google/play/billing/migrate-gpblv6) all new apps and updates to existing apps must use Billing Library version 6 or newer by Aug 31, 2024.

This library is currently at v5.2.1

https://github.com/chargebee/chargebee-react-native/blob/daeb1747a90e0fea091f42d943124b8b199062fc/android/build.gradle#L88

**Comment by cb-haripriyan** [comment]
Hi @MarkAuderli 
This is on our radar and we would be updating this library soon. We will communicate once its out.

**Comment by talhatsk** [comment]
> Hi @MarkAuderli This is on our radar and we would be updating this library soon. We will communicate once its out.

waiting for the update.

**Comment by sahanap92** [comment]
Please update the play library.

**Comment by chethana-shastry-ps** [comment]
Hi chargebee team, will you please update this at the earliest, we have used your SDK in our react native app. Waiting for your response

**Comment by cb-haripriyan** [comment]
Hi @talhatsk , @sahanap92 , @chethana-shastry-ps  - 
We are working on it and expect it to be out for all relevant sdks by 20th Jul.

**Comment by cb-palanim** [comment]
Release 3.0.0-beta.1 (beta) and 2.5.0 (main) are updated with google billing client 6.2.1.
