### ISSUE TITLE
Error with Using ChargeBee API's 2.0 

### ISSUE THREAD

**Issue by snevula123456** [chargebee/chargebee-react-native#20]
Initially, I was using 1 Version APIs to fetch and Subscribe, I haven't faced any issues, but now I am Using 2 Version APIs to fetch the response and Tried to implement it with @chargebee/Chargebee-react-native. I am facing the error as 
**Error** : 
"Subscription with New Item Model cannot be created using this Endpoint, Please use create a subscription with item endpoint to create subscription "

![Screenshot at Jul 14 18-53-58](https://user-images.githubusercontent.com/25643849/125629577-2e2b9244-84f4-480e-ae4f-4197f0bfa668.png)

Attaching Screenshot for Ref: :
[https://lh6.googleusercontent.com/hbin13_kfMjYCveOVgAwpswJmGGsq11unmhdSkPhSSlwou0Ei44AJKxXnmRQERuxlwaV_gn2ReU7F9dKzKJONL_HbnrkvRfHVSMRvfe9VBEWkuc_D8eNrNEF9mYJ-lJtDqL_L3yx-Vis1_WnBfzJf-w3pUydOj6x5b4FYJ9mBBB8DgjRzllDaEdQ4ltMo9-co9Z3HZOMRNSx=w319-h639](url)

` <CheckoutCart
      success={(hostedPageId: string) => successfulPurchase(hostedPageId)}
      step={(stepName: string) => handleStep(stepName)}
      site={site}  // site Name
      planName={name} // Plan Name
      planId={id}.  // I am Passing plan Id
 />`

- Attaching Postman Response screenshot.
- Thanks in Advance.
![Screenshot at Jul 14 18-35-08](https://user-images.githubusercontent.com/25643849/125628057-5d2de077-9f03-4dc5-bc6d-090aeada4934.png)

**Comment by harishbharadwaj** [comment]
Latest version for V2 has been published. Please have a look at the example app for reference and revert for any issues.

**Comment by cb-harishbharadwaj** [comment]
Latest version for V2 has been published. Please have a look at the example app for reference and revert for any issues.
